"""Initial migration

Revision ID: 870e8a9706a0
Revises: 9bcb37bb1a55
Create Date: 2025-07-29 19:33:22.249255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870e8a9706a0'
down_revision: Union[str, Sequence[str], None] = '9bcb37bb1a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('grade_date', sa.Date(), nullable=True))
    op.drop_column('grades', 'date_of')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date_of', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('grades', 'grade_date')
    # ### end Alembic commands ###
